version: '3.8'
services:
  iam-redis:
    image: redis:8.4.0
    ports:
      - "6379:6379"
    container_name: iam-redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-secure.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    networks:
      - iam-network

  iam-fastapi:
    build: .
    environment:
      - REDIS_HOST=iam-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Replace_This_With_A_Super_Long_Random_String_Or_Env_Var
    networks:
      - iam-network
    ports:
          - "8000:8000"

volumes:
  redis_data:

networks:
  iam-network:


# Do NOT expose the port in your docker-compose.yml unless absolutely necessary.
# ports:
#   - "6379:6379"  # Anyone on the internet can try to brute force your Redis