
##################################
# Minimal redis.conf for LOCAL DEV
# (Do NOT use in shared, staging, or production)
##################################
# Keep protected mode on as an extra safety net.
#protected-mode yes

# Default redis port.
port 6379

# NO ACL
# NO passwords
# NO maxmemory limits
# NO persistence
# NO logging