##################################
# NETWORK & SECURITY
##################################

# 1. Bind to all interfaces INSIDE the container.
# Note: Security is handled by Docker Network isolation, not this IP bind.
bind 0.0.0.0

# 2. Enable Protected Mode (Safety net)
protected-mode yes

# 3. Change the default port (Optional, but good for obscurity)
port 6379

# 4. AUTHENTICATION (OWASP A07)
# Use a very strong password (100+ bits of entropy).
# Redis is fast; attackers can guess 150k passwords per second.
#requirepass "VJ7RHN6uekzKEcibu6DK33LuyZGonD2mUjppsY5F5YogwBe2m7odQqWTXgisM55mjSTs9"

#################################### ACL #######################################

# 1. THE ADMIN USER
# Syntax: user <username> <status> <password> <commands> <keys> <channels>
#
# >adminpass    : Sets the password to 'adminpass'
# +@all         : Allows all command categories
# ~* : Allows access to all keys
# &* : Allows access to all Pub/Sub channels
user iam on >VJ7RHN6uekzKEcibu6DK33LuyZGonD2mUjppsY5F5YogwBe2m7odQqWTXgisM55mjSTs9 +@all ~* &*

# 2. THE DEFAULT USER (Restricted)
# It is best practice to restrict the 'default' user so unauthenticated 
# or legacy connections cannot do damage.
#
# >userpass     : Sets password to 'userpass'
# +@read        : Allows read-only commands (GET, MGET, etc.)
# -keys         : Explicitly forbid the 'KEYS' command (performance danger)
# ~public:* : Only allow access to keys starting with "public:"
user default on >userpass +@read -keys ~public:*

##################################
# ATTACK SURFACE REDUCTION (OWASP A05)
##################################

# 5. Disable Dangerous Commands
# Prevents an attacker who gets in from wiping data or reconfiguring the server.
# rename-command FLUSHDB ""
# rename-command FLUSHALL ""
# rename-command DEBUG ""

# 6. Rename Configuration Commands
# Prevents attackers from using 'CONFIG SET' to make the server write 
# a malicious file (RCE) or change the password.
#rename-command CONFIG "b840fc02d524045429941cc15f59e41cb7be6c52"

##################################
# MEMORY & DOS PROTECTION (OWASP A04)
##################################

# 7. Max Memory Limit
# If you don't set this, Redis can eat all RAM and crash your server (DoS).
# Set this based on your container limits (e.g., 256mb).
maxmemory 256mb

# 8. Eviction Policy
# When full, delete the oldest keys to keep the IAM running.
# 'volatile-lru' only deletes keys with an Expiry (like User Sessions).
maxmemory-policy volatile-lru

##################################
# PERSISTENCE & LOGGING
##################################

# 9. Append Only File (Better Durability)
appendonly yes
appendfilename "appendonly.aof"

# 10. Logging
loglevel notice