##################################
# NETWORK & SECURITY
##################################

# 1. Bind to all interfaces INSIDE the container.
# Note: Security is handled by Docker Network isolation, not this IP bind.
bind 0.0.0.0

# 2. Enable Protected Mode (Safety net)
protected-mode yes

# 3. Change the default port (Optional, but good for obscurity)
port 6300

#################################### ACL #######################################

# 1. THE ADMIN USER
# Syntax: user <username> <status> <password> <commands> <keys> <channels>
#
# >adminpass    : Sets the password to 'adminpass'
# +@all         : Allows all command categories
# ~* : Allows access to all keys
# &* : Allows access to all Pub/Sub channels
user iam on >VJ7RHN6uekzKEcibu6DK33LuyZGonD2mUjppsY5F5YogwBe2m7odQqWTXgisM55mjSTs9 +@all ~* &*

# 2. THE DEFAULT USER (Restricted)
# It is best practice to restrict the 'default' user so unauthenticated 
# or legacy connections cannot do damage.
#
# >userpass     : Sets password to 'userpass'
# +@read        : Allows read-only commands (GET, MGET, etc.)
# -keys         : Explicitly forbid the 'KEYS' command (performance danger)
# ~public:* : Only allow access to keys starting with "public:"

# Prevents user from using 'CONFIG SET' to make the server write 
# Prevents an user who gets in from wiping data or reconfiguring the server.
user default on >3bfueHb3jvYPiWFNrzNCCoo3D2MiRipEot6XgZdqDv4YeXupFbKanyQoSMptHMxs +@read -keys ~public:*

##################################
# MEMORY & DOS PROTECTION (OWASP A04)
##################################

# 7. Max Memory Limit
# If you don't set this, Redis can eat all RAM and crash your server (DoS).
# Set this based on your container limits (e.g., 256mb).
maxmemory 256mb

# 8. Eviction Policy
# When full, delete the oldest keys to keep the IAM running.
# 'volatile-lru' only deletes keys with an Expiry (like User Sessions).
maxmemory-policy volatile-lru

##################################
# PERSISTENCE & LOGGING
##################################

# 9. Append Only File (Better Durability)
# Persistence on so you don’t lose test data between restarts.
appendonly yes
appendfilename "appendonly.aof"

# 10. Logging
# Keep logs readable.
loglevel notice